on:
  workflow_dispatch:

name: Test OS-C Tokens

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish in PyPi Test
        run: |
          echo ${{ secrets.OSC_PYPI_TEST_TOKEN }}
          echo ${{secrets.OSC_PYPI_TEST_USER }}
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.OSC_PYPI_TEST_TOKEN }}
          poetry config --list