on:
  workflow_dispatch:

name: Test OS-C Tokens

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Test secrets
        run: |
          echo 'The GitHub Action Secret will be masked:  '
          echo ${{ secrets.OSC_PYPI_TEST_TOKEN }}
          echo ${{ secrets.OSC_PYPI_TEST_USER }}
          echo ${{ secrets.OSC_PYPI_TOKEN }}
          echo ${{ secrets.OSC_PYPI_USER }}
