on:
  workflow_dispatch:

name: Test OS-C Tokens

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish in PyPi Test
        env:
          TESTPYPI_URL: https://test.pypi.org/legacy/
          TESTPYPI_USERNAME: ${{ secrets.OSC_PYPI_TEST_USER }}
          TESTPYPI_PASSWORD: ${{ secrets.OSC_PYPI_TEST_TOKEN }}
        run: |
          poetry config repositories.testpypi $TESTPYPI_URL
          poetry publish -r testpypi --username $TESTPYPI_USERNAME --password $TESTPYPI_PASSWORD --dry-run