on:
  workflow_dispatch:

name: Test OS-C Tokens

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish in PyPi Test
        run: |
          export POETRY_REPOSITORIES_TESTPYPI_URL=https://test.pypi.org/legacy/
          export POETRY_HTTP_BASIC_TESTPYPI_USERNAME=${{secrets.OSC_PYPI_TEST_USER }}
          export POETRY_HTTP_BASIC_TESTPYPI_PASSWORD=${{secrets.OSC_PYPI_TEST_TOKEN }}
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config --list